security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        in_memory:
            memory:
                users:
                    admin:
                        # Password is obviously.. internations :)
                        password: $2y$13$LbmoKMSw6a52sr9Pk/oct.YLCs7NoXlJsmJUg7Ppr/x3R/H2EHBdS
                        roles: 'ROLE_ADMIN'
    role_hierarchy:
        ROLE_ADMIN: [ROLE_API]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # anonymous: true
            http_basic: true
            provider: in_memory
    access_control:
        # - { path: ^/admin, roles: ROLE_API }
        - { path: ^/, roles: ROLE_API }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13
